### ISSUE TITLE
[mini-todo ver 2.0] Task List

### ISSUE THREAD

**Issue by eezn** [eezn/spring-mini-todo#62]
### 사전 작업
- [x] 추가할 기능 확정, 구현 단위 쪼개기
- [x] #47 
- [x] #67 점검, 리펙토링, 교통정리
- [x] Git-flow 적용 / 브랜치 용도별로 분리

### 추가 기능
- #97
    - 공통 템플릿 수정
- release-2.2 (Back-end)
    - 유저 페이지, 개인정보 수정 기능 추가
        - [x] #65 
        - [x] #66 
    - 유저별 카테고리, 우선순위 추가 편집
    - 관리자 페이지
- release-2.3 (Back-end, Service)
    - 유저 출석 추가
    - 스케줄링 - FCFS, SJF, HRN, SRT 추가

### 그 외
- [ ] **프론트엔드 갈아엎기**
  - [ ] 전체 페이지 기본 레이아웃
  - [ ] Bootstrap or Tailwind CSS
  - [ ] 동적 페이지 고민
- [ ] 에러 페이지
- [ ] 유저 SNS 링크 (유저 테이블에 항목 추가)

---
### 아이디어 메모
- mindset
- achievement
- self-evaluation
- peer-evaluation
- group todo

### 메모
-
